GitHub Actions

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -78,6 +78,7 @@ jobs:
         uses: actions/checkout@v2
       - name: Set up Python ${{ env.DEFAULT_PYTHON }}
         uses: actions/setup-python@v2
+        id: python
         with:
           python-version: ${{ env.DEFAULT_PYTHON }}
       - name: Restore Python virtual environment
@@ -92,8 +93,9 @@ jobs:
             hashFiles('homeassistant/package_constraints.txt') }}
       - name: Fail job if Python cache restore failed
         if: steps.cache-venv.outputs.cache-hit != 'true'
-        run:
-          echo "Failed to restore Python virtual environment from cache" exit 1
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
       - name: Restore pre-commit environment from cache
         id: cache-precommit
         uses: actions/cache@v2
@@ -103,8 +105,9 @@ jobs:
             ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
       - name: Fail job if cache restore failed
         if: steps.cache-venv.outputs.cache-hit != 'true'
-        run:
-          echo "Failed to restore Python virtual environment from cache" exit 1
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
       - name: Run executables check
         run: |
           . venv/bin/activate
