GitHub Actions

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -598,3 +598,82 @@ jobs:
         run: |
           . venv/bin/activate
           pylint homeassistant
+
+  mypy:
+    name: Check mypy
+    runs-on: ubuntu-latest
+    needs: prepare-tests
+    strategy:
+      matrix:
+        python-version: [3.7]
+    container: homeassistant/ci-azure:${{ matrix.python-version }}
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2
+      - name: Restore Python ${{ matrix.python-version }} virtual environment
+        id: cache-venv
+        uses: actions/cache@v2
+        with:
+          path: venv
+          key: >-
+            ${{ runner.os }}-base-venv-${{ matrix.python-version }}-${{
+            hashFiles('requirements.txt') }}-${{
+            hashFiles('requirements_test_all.txt') }}-${{
+            hashFiles('homeassistant/package_constraints.txt') }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: Run mypy
+        run: |
+          . venv/bin/activate
+          mypy homeassistant
+
+  pytest:
+    name: Check pytest
+    runs-on: ubuntu-latest
+    needs: prepare-tests
+    strategy:
+      matrix:
+        group: [1, 2, 3, 4, 5]
+        python-version: [3.7, 3.8]
+    container: homeassistant/ci-azure:${{ matrix.python-version }}
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2
+      - name: Restore Python ${{ matrix.python-version }} virtual environment
+        id: cache-venv
+        uses: actions/cache@v2
+        with:
+          path: venv
+          key: >-
+            ${{ runner.os }}-base-venv-${{ matrix.python-version }}-${{
+            hashFiles('requirements.txt') }}-${{
+            hashFiles('requirements_test_all.txt') }}-${{
+            hashFiles('homeassistant/package_constraints.txt') }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: Run pytest
+        run: |
+          . venv/bin/activate
+          pip install pytest-split
+          pytest \
+            --timeout=9 \
+            --durations=10 \
+            -n auto \
+            --dist=loadfile \
+            --splits 5 \
+            --group ${{ matrix.group }} \
+            --cov homeassistant \
+            --cov-report html \
+            -qq \
+            -o console_output_style=count \
+            -p no:sugar \
+            tests
+      - name: Check dirty
+        run: |
+          ./script/check_dirty
